### ISSUE TITLE
cache.push is not a function

### ISSUE THREAD

**Issue by wcoebergh** [allenhwkim/angular-jsdoc#109]
Title says it all, no other errors or messages, just 'cache.push is not a function'.

Here is the full error log:

```
/Users/WouterCoebergh/Documents/git/slim-core/node_modules/angular-jsdoc/angular-template/publish.js:253
        cache.push(doclet);
              ^

TypeError: cache.push is not a function
    at /Users/WouterCoebergh/Documents/git/slim-core/node_modules/angular-jsdoc/angular-template/publish.js:253:15
    at each (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/taffydb/taffy.js:87:17)
    at Object.<anonymous> (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/taffydb/taffy.js:1109:7)
    at Object.API.(anonymous function) [as each] (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/taffydb/taffy.js:127:18)
    at Object.exports.publish (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/angular-jsdoc/angular-template/publish.js:244:10)
    at Object.module.exports.cli.generateDocs (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/cli.js:430:39)
    at Object.module.exports.cli.processParseResults (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/cli.js:383:20)
    at module.exports.cli.main (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/cli.js:227:14)
    at Object.module.exports.cli.runCommand (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/cli.js:180:5)
    at /Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/jsdoc.js:103:9
    at Object.<anonymous> (/Users/WouterCoebergh/Documents/git/slim-core/node_modules/jsdoc/jsdoc.js:104:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by darkmavis1980** [comment]
I have the same issue, did anybody found a solution?

**Comment by anx-ckreuzberger** [comment]
Same issue

**Comment by mOewa** [comment]
Same issue, anyone found a solution?

**Comment by allenhwkim** [comment]
This line causes an error.
https://github.com/allenhwkim/angular-jsdoc/blob/4089c97d1226df923b20bd7cc5b4506143669600/angular-template/publish.js#L252

I am not sure why this is not an array.
