### ISSUE TITLE
jsdoc aborts with error when function has no parameters

### ISSUE THREAD

**Issue by jansc** [allenhwkim/angular-jsdoc#26]
I tried angular-jsdoc in a project where a function within a service had no parameters. jsdoc will then abort with an error message.

I'm sorry that I can't provide a pull request to fix this issue, but I hope this information might help you to track it down.

Steps to reproduce:

I created an empty procject with just one js-file and

```javascript
(function () {
  'use strict';

  angular.module('app').service('testService', testService);

  /**
   * The siteLanguageServices provides information about available languges
   * of a site.
   *
   * @memberof app
   * @ngdoc service
   * @name testService
   * @param {$http} Test
   * @ngInject
   */

  function testService ($http) {
  }
  
   /**
    * @memberof testService
    * @method test
    * ///// NO param jsdoc tag here
    */
   function test() {
   }
})();
```

Command to start jsdoc:
```bash
node_modules/jsdoc/jsdoc.js   --configure node_modules/angular-jsdoc/common/conf.json   --template node_modules/angular-jsdoc/default   --destination docs --recurse index.js
```

Error message:
```
jsTemplate error in line 108
jsTemplate error in line 49
/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:72
    throw e;
          ^
TypeError: Cannot read property 'map' of undefined
    at eval (eval at <anonymous> (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:56:12), <anonymous>:3:7095)
    at Array.forEach (native)
    at eval (eval at <anonymous> (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:56:12), <anonymous>:3:6736)
    at jsTemplate [as include] (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:67:18)
    at eval (eval at <anonymous> (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:56:12), <anonymous>:3:3238)
    at jsTemplate (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/node_modules/js-template/index.js:67:18)
    at generate (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/default/publish.js:99:14)
    at /Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/default/publish.js:180:5
    at Array.forEach (native)
    at Object.exports.publish (/Users/jans/dev/angular-jsdoc-test/node_modules/angular-jsdoc/default/publish.js:176:11)
```

When I add a @param line to the `test()`-function, jsdoc works as expected.

**Comment by allenhwkim** [comment]
@jansc Thanks for reporting the bug. I made a fix

**Comment by jansc** [comment]
Thanks for the quick response and for your effort on angular-jsdoc :-)

**Comment by allenhwkim** [comment]
@jansc If you want, I can add you as a contributor, so that you can directly fix the code even without asking me.

**Comment by jansc** [comment]
Hm. I see that you commited the contents of angular-jsdoc/default/docs as part of the fix. Was this by accident?
I'd be happy to contribute to angular-jsdoc, but I'm not sure how much time I can put into the project. If things go well, we plan to use it for a bigger project at our company. Then I might be able to make some contributions.

**Comment by allenhwkim** [comment]
default/docs is to show users how generated document looks like. It was
intentional. I would be happy if you join the team.

**Comment by jansc** [comment]
Ok, thanks :)

**Comment by jansc** [comment]
It works fine now. Thanks for the fix.
