### ISSUE TITLE
Error executing test scripts on Windows 8

### ISSUE THREAD

**Issue by reloaded** [allenhwkim/angular-jsdoc#69]
I'm getting a rather slim error message while trying to execute test.js on Windows.

```
C:\Users\reloaded\PhpstormProjects\angular-jsdoc>node test.js
angularJsdoc Running command
 node_modules\jsdoc\jsdoc.js --configure common/test_conf.json --template C:\Users\reloaded\PhpstormProjects\angular-jsdoc\default --destination default/docs --readme sample-codes/README.md --recurse sample-codes
internal/child_process.js:298
    throw errnoException(err, 'spawn');
    ^

Error: spawn UNKNOWN
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at runCommand (C:\Users\reloaded\PhpstormProjects\angular-jsdoc\index.js:15:15)
    at angularJsdoc (C:\Users\reloaded\PhpstormProjects\angular-jsdoc\index.js:52:3)
    at Object.<anonymous> (C:\Users\reloaded\PhpstormProjects\angular-jsdoc\test.js:3:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

```
C:\Users\reloaded\PhpstormProjects\angular-jsdoc>node -v
v5.6.0
```

**Comment by Zemke** [comment]
It fails [on this line](https://github.com/allenhwkim/angular-jsdoc/blob/master/index.js#L15) when spawning a new child process. A solution might be [this](http://stackoverflow.com/a/17537559). Please report back. If it works, you can gladly submit a PR.

**Comment by reloaded** [comment]
@Zemke  Your post helped a lot, I used various answers and comments on that StackOverflow article to come up with a solution that is tested to work on Windows.

I will submit a PR.

**Comment by reloaded** [comment]
@Zemke  could you review and merge in my pull request?

**Comment by Zemke** [comment]
Perfect! 👍

I tested this on OS X and it worked. So, now that it works in Unix and Windows environment, we should have a cross-platform solution. Thank you and also thanks for fixing the white-spaces!
