### ISSUE TITLE
Not work on Windows 7

### ISSUE THREAD

**Issue by yarkovaleksei** [allenhwkim/angular-jsdoc#83]
App crashed with error:

`````` bash
Error: Command `node_modules/jsdoc/jsdoc.js -c node_modules/angular-jsdoc/common/conf.json -t node_modules/angular-jsdoc/angular-template -d ./docs ./README.md -r ./src/js` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:100:13)
    at ChildProcess.emit (events.js:185:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at Pipe._onclose (net.js:475:12)```

On Linux its good work. Please fix it!
``````

**Comment by Zemke** [comment]
Was this run as a Gulp task? If so, could you please add the task definition in your `gulpfile`?

**Comment by yarkovaleksei** [comment]
Gulp task in file **./gulp/gulp-tasks/docs.js**
```javascript
module.exports = function (gulp, plugins, options) {
    return function () {
		gulp.task('docs', plugins.shell.task([
			'node_modules/jsdoc/jsdoc.js '+
			'-c node_modules/angular-jsdoc/common/conf.json '+   	// options
			'-t node_modules/angular-jsdoc/angular-template '+   	// template
			'-d docs '+                           					// output DOCS folder
			'./README.md ' +                            			// use README.md how index.html
			'-r src/js'                								// source folder
		]));
    };
};
```

This is defined 'docs' task:
```javascript
var gulp = require('gulp');
var plugins = require('gulp-load-plugins')();
plugins.shell = require('gulp-shell');
var options = require('./gulp/options');

function getTask(task) {
	return require('./gulp/gulp-tasks/' + task)(gulp, plugins, options);
}

gulp.task('docs', getTask('docs'));
```

**Comment by allenhwkim** [comment]
these path does not looks like windows path for me `node_modules/angular-jsdoc/common/conf.json`.
Shouldnt' it be `node_modules\angular-jsdoc\common\conf.json` instead?

If you want it for both system, please use `path.join` instead of using specifying directly.

e.g., path.jon('node_modules', 'angular-jsdoc', 'common', 'conf.json')

**Comment by yarkovaleksei** [comment]
Use path.join:
```javascript
module.exports = function (gulp, plugins, options) {
	return function () {
		var path = require('path');
		var script = path.join('node_modules','jsdoc','jsdoc.js');
		var conf = path.join('node_modules','angular-jsdoc','common', 'conf.json');
		var template = path.join('node_modules','angular-jsdoc','angular-template');
		var jsdir = path.join('src','js');
		gulp.task('docs', plugins.shell.task([
			script+' -c '+conf+' -t '+template+' -d docs README.md -r '+jsdir
		]));
	};
};
```

Now when task run the file open  **node_modules/jsdoc/jsdoc.js** in the default editor .

**Comment by allenhwkim** [comment]
Still you see error?

**Comment by yarkovaleksei** [comment]
No, there is no error is now. Just file **node_modules/jsdoc/jsdoc.js** it is not satisfied, and opens in the editor. On Linux you are running.

**Comment by JonathanRowley** [comment]
if you change the above to: 
```
module.exports = function (gulp, plugins, options) {
    return function () {
        var path = require('path');
        var script = path.join('node_modules','jsdoc','jsdoc.js');
        var conf = path.join('node_modules','angular-jsdoc','common', 'conf.json');
        var template = path.join('node_modules','angular-jsdoc','angular-template');
        var jsdir = path.join('src','js');
        gulp.task('docs', plugins.shell.task([
            'node '+script+' -c '+conf+' -t '+template+' -d docs README.md -r '+jsdir
        ]));
    };
};
```

(basically just prepend the script directory with 'node', it should run fine on windows and mac. Not tested Linux)
