### ISSUE TITLE
angular-template error in compilation

### ISSUE THREAD

**Issue by ticktockreed** [allenhwkim/angular-jsdoc#86]
A recent update has introduced the following error on compilation.

The error:
>> C:\Sites\TEST\OBA\node_modules\angular-jsdoc\node_modules\angular-template\index.js:140
>>         throw e;
>>               ^
>> SyntaxError: Unexpected reserved word
>>     at Object.Function (<anonymous>)
>>     at templateFunc (C:\Sites\TEST\OBA\node_modules\angular-jsdoc\node_modules\js-template\index.js:56:12)
>>     at jsTemplate (C:\Sites\TEST\OBA\node_modules\angular-jsdoc\node_modules\js-template\index.js:65:18)
>>     at angularTemplate (C:\Sites\TEST\OBA\node_modules\angular-jsdoc\node_modules\angular-template\index.js:128:14)
>>     at generateSourceFiles (C:\Sites\TEST\OBA\node_modules\angular-jsdoc\angular-template\publish.js:100:16)
>>     at Object.exports.publish (C:\Sites\TEST\OBA\node_modules\angular-jsdoc\angular-template\publish.js:283:3)
>>     at Object.module.exports.cli.generateDocs (C:\Sites\TEST\OBA\node_modules\jsdoc\cli.js:430:39)
>>     at Object.module.exports.cli.processParseResults (C:\Sites\TEST\OBA\node_modules\jsdoc\cli.js:383:20)
>>     at module.exports.cli.main (C:\Sites\TEST\OBA\node_modules\jsdoc\cli.js:227:14)
>>     at Object.module.exports.cli.runCommand (C:\Sites\TEST\OBA\node_modules\jsdoc\cli.js:180:5)
>>     at C:\Sites\TEST\OBA\node_modules\jsdoc\jsdoc.js:103:9
>>     at Object.<anonymous> (C:\Sites\TEST\OBA\node_modules\jsdoc\jsdoc.js:104:3)
>>     at Module._compile (module.js:456:26)
>>     at Object.Module._extensions..js (module.js:474:10)
>>     at Module.load (module.js:356:32)
>>     at Function.Module._load (module.js:312:12)
Warning: jsdoc terminated with a non-zero exit code Use --force to continue.

**My Grunt task:**

        // Create Javascript documentation
        jsdoc : {
            dist : {
                src: ['app/views/*/*.js','app/directives/*/*.js','app/services/*/*.js'],
                options: {
                    destination: 'documentation/jsdoc',
                    configure: 'node_modules/angular-jsdoc/common/conf.json',
                    template: 'node_modules/angular-jsdoc/angular-template',
                    tutorial: 'tutorials',
                    readme: './README.md'
                }
            }
        },

Removing the template uses the default jsdoc template and works with no issues.

I can't tell whether this is due to a change in angular-jsdoc, jsdoc, or grunt-jsdoc. Could you please advise?

Thanks in advance

**Comment by ticktockreed** [comment]
Thanks for taking the time to look at this @FDIM. I have implemented the fix and it works! Great :). When will you deploy to NPM?

**Comment by FDIM** [comment]
Unfortunately I do not have access to this repo, you'll have to wait for @allenhwkim :)

**Comment by allenhwkim** [comment]
@FDIM, you are already a co-owner of this repo.
![image](https://cloud.githubusercontent.com/assets/1437734/15799306/41bec1c4-2a26-11e6-9ccb-3b31d541362f.png)

**Comment by FDIM** [comment]
True, but the bugfix is in jsdoc :)

**Comment by allenhwkim** [comment]
@FDIM true, sorry about that. 1.4.2 has been published
